services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pnpm start
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
      
    environment:
      - TYPEORM_CONNECTION=${DATABASE_CONNECTION}
      - TYPEORM_HOST=${DATABASE_HOST}
      - TYPEORM_USERNAME=${DATABASE_USERNAME}
      - TYPEORM_PASSWORD=${DATABASE_PASSWORD}
      - TYPEORM_DATABASE=${DATABASE_DB}
      - TYPEORM_PORT=${DATABASE_PORT}
      - TYPEORM_LOGGER=advanced-console
      - TYPEORM_LOGGING=true
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_ENTITIES=app/models/**/*.js
      - TYPEORM_ENTITIES_DIR=app/models
      - NVD_API_URL=${API_URL}
      - NVD_API_KEY=${API_KEY}
      - APP_NAME=${APP_NAME}
      - APP_SCHEMA=${APP_SCHEMA}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_SECRET=${APP_SECRET}
    restart: always

